### ISSUE TITLE
News display

### ISSUE THREAD

**Issue by blakeneely** [blakeneely/project1#8]
## User Story
As a user I want to see important news immediately

## Acceptance Criteria
- [x] Use espn api to get news
- [x] add news section to index.html
- [x] build example layout for each article headline

## Tasks
1. Create ajax call with espn api 
2. Console log response
3. Use Bulma docs to create Section and Container below Hero
4. Give container ID #news-container for JS later
5. Use Bulma docs to create sample elements to display news (cards most likely)
6. Temporarily display cards in News Container for JS looping later
